name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux-and-wasm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/i-a-s/iabuild-env:latest
    strategy:
      fail-fast: false
      matrix:
        target: [linux-x64, linux-arm64, wasm]
    steps:
      - uses: actions/checkout@v4

      - name: Update Vcpkg Repo
        run: |
          cd /opt/vcpkg
          git fetch --all
          git pull origin master

      - name: Configure
        run: cmake --preset ${{ matrix.target }}

      - name: Build
        run: cmake --build --preset ${{ matrix.target }} --config Release
