name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux-and-wasm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/i-a-s/iabuild-env:latest
    strategy:
      fail-fast: false
      matrix:
        target: [x64-linux]
        
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenSSL v3 (System)
        run: sudo dnf install -y openssl-devel

      - name: Configure
        run: cmake --preset ${{ matrix.target }}

      - name: Build
        run: cmake --build --preset ${{ matrix.target }} --config Release

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        target: [x64-windows]

    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: cmake --preset ${{ matrix.target }}

      - name: Build
        run: cmake --build --preset ${{ matrix.target }} --config Release